/* eslint-disable */
// AUTO-GENERATED — do not edit by hand.
// Regenerate with: pnpm --filter @opensea/api-types run generate
//
// Re-exports every `components.schemas.*` entry from the OpenAPI spec as a
// named type so downstream consumers (SDK, CLI, stream, etc.) never hit a
// missing-export when the spec gains a new schema.

import type { components } from "./generated.js"

type Schemas = components["schemas"]

export type AccountResolveResponse = Schemas["AccountResolveResponse"]
export type AccountResponse = Schemas["AccountResponse"]
export type AccountSearchResponse = Schemas["AccountSearchResponse"]
export type AdditionalRecipient = Schemas["AdditionalRecipient"]
export type Address = Schemas["Address"]
export type AdvancedOrder = Schemas["AdvancedOrder"]
export type AgentBindingResponse = Schemas["AgentBindingResponse"]
export type AgentNftResponse = Schemas["AgentNftResponse"]
export type AssetEventsResponse = Schemas["AssetEventsResponse"]
export type AssetIdentifierResponse = Schemas["AssetIdentifierResponse"]
export type AssetMetadataResponse = Schemas["AssetMetadataResponse"]
export type AssetQuantityInput = Schemas["AssetQuantityInput"]
export type AssetReceiptResponse = Schemas["AssetReceiptResponse"]
export type AuthScope = Schemas["AuthScope"]
export type BasicOrderParameters = Schemas["BasicOrderParameters"]
export type BatchCollectionsRequest = Schemas["BatchCollectionsRequest"]
export type BatchNftsRequest = Schemas["BatchNftsRequest"]
export type BatchTokensRequest = Schemas["BatchTokensRequest"]
export type BidderResponse = Schemas["BidderResponse"]
export type BuildOfferRequest = Schemas["BuildOfferRequest"]
export type BuildOfferResponse = Schemas["BuildOfferResponse"]
export type CancelRequest = Schemas["CancelRequest"]
export type CancelResponse = Schemas["CancelResponse"]
export type ChainIdentifier = Schemas["ChainIdentifier"]
export type ChainListResponse = Schemas["ChainListResponse"]
export type ChainResponse = Schemas["ChainResponse"]
export type ClosedPositionResponse = Schemas["ClosedPositionResponse"]
export type ClosedPositionsResponse = Schemas["ClosedPositionsResponse"]
export type CollectionBatchResponse = Schemas["CollectionBatchResponse"]
export type CollectionCriteria = Schemas["CollectionCriteria"]
export type CollectionDetailedResponse = Schemas["CollectionDetailedResponse"]
export type CollectionHolderResponse = Schemas["CollectionHolderResponse"]
export type CollectionHoldersPaginatedResponse =
  Schemas["CollectionHoldersPaginatedResponse"]
export type CollectionInner = Schemas["CollectionInner"]
export type CollectionObject = Schemas["CollectionObject"]
export type CollectionOfferAggregateResponse =
  Schemas["CollectionOfferAggregateResponse"]
export type CollectionOfferAggregatesPaginatedResponse =
  Schemas["CollectionOfferAggregatesPaginatedResponse"]
export type CollectionPaginatedResponse = Schemas["CollectionPaginatedResponse"]
export type CollectionRarity = Schemas["CollectionRarity"]
export type CollectionResponse = Schemas["CollectionResponse"]
export type CollectionSearchResponse = Schemas["CollectionSearchResponse"]
export type CollectionStatsResponse = Schemas["CollectionStatsResponse"]
export type Consideration = Schemas["Consideration"]
export type ConsiderationItem = Schemas["ConsiderationItem"]
export type ConsiderationObject = Schemas["ConsiderationObject"]
export type Contract = Schemas["Contract"]
export type ContractCriteria = Schemas["ContractCriteria"]
export type ContractInner = Schemas["ContractInner"]
export type ContractResponse = Schemas["ContractResponse"]
export type CreateListingActionsRequest = Schemas["CreateListingActionsRequest"]
export type CreateListingActionsResponse =
  Schemas["CreateListingActionsResponse"]
export type Criteria = Schemas["Criteria"]
export type CriteriaObject = Schemas["CriteriaObject"]
export type CriteriaRequest = Schemas["CriteriaRequest"]
export type CriteriaResolver = Schemas["CriteriaResolver"]
export type CrossChainFulfillmentRequest =
  Schemas["CrossChainFulfillmentRequest"]
export type CrossChainFulfillmentResponse =
  Schemas["CrossChainFulfillmentResponse"]
export type CrossChainPaymentToken = Schemas["CrossChainPaymentToken"]
export type DropDeployReceiptResponse = Schemas["DropDeployReceiptResponse"]
export type DropDeployRequest = Schemas["DropDeployRequest"]
export type DropDeployResponse = Schemas["DropDeployResponse"]
export type DropDetailedResponse = Schemas["DropDetailedResponse"]
export type DropMintRequest = Schemas["DropMintRequest"]
export type DropMintResponse = Schemas["DropMintResponse"]
export type DropPaginatedResponse = Schemas["DropPaginatedResponse"]
export type DropResponse = Schemas["DropResponse"]
export type DropStageResponse = Schemas["DropStageResponse"]
export type Eip3009Fields = Schemas["Eip3009Fields"]
export type Event = Schemas["Event"]
export type EventBase = Schemas["EventBase"]
export type Fee = Schemas["Fee"]
export type FloorPriceHistoryResponse = Schemas["FloorPriceHistoryResponse"]
export type FloorPricePointResponse = Schemas["FloorPricePointResponse"]
export type FulfillAdvancedOrder = Schemas["FulfillAdvancedOrder"]
export type FulfillAvailableAdvancedOrders =
  Schemas["FulfillAvailableAdvancedOrders"]
export type FulfillAvailableOrders = Schemas["FulfillAvailableOrders"]
export type FulfillBasicOrder = Schemas["FulfillBasicOrder"]
export type FulfillListingResponse = Schemas["FulfillListingResponse"]
export type FulfillOrder = Schemas["FulfillOrder"]
export type FulfillerObject = Schemas["FulfillerObject"]
export type Fulfillment = Schemas["Fulfillment"]
export type FulfillmentComponent = Schemas["FulfillmentComponent"]
export type FulfillmentData = Schemas["FulfillmentData"]
export type FullfillListingRequest = Schemas["FullfillListingRequest"]
export type FullfillmentDataRequest = Schemas["FullfillmentDataRequest"]
export type GetOrderResponse = Schemas["GetOrderResponse"]
export type InstantApiKeyResponse = Schemas["InstantApiKeyResponse"]
export type IntervalStat = Schemas["IntervalStat"]
export type Item = Schemas["Item"]
export type JsonNode = Schemas["JsonNode"]
export type LinkWalletSiwxRequest = Schemas["LinkWalletSiwxRequest"]
export type Listing = Schemas["Listing"]
export type ListingItem = Schemas["ListingItem"]
export type ListingObject = Schemas["ListingObject"]
export type ListingOrOffer = Schemas["ListingOrOffer"]
export type ListingPrice = Schemas["ListingPrice"]
export type ListingPriceInput = Schemas["ListingPriceInput"]
export type ListingsResponse = Schemas["ListingsResponse"]
export type MatchAdvancedOrders = Schemas["MatchAdvancedOrders"]
export type MatchOrders = Schemas["MatchOrders"]
export type MetadataIngestionError = Schemas["MetadataIngestionError"]
export type Nft = Schemas["Nft"]
export type NftAnalyticsResponse = Schemas["NftAnalyticsResponse"]
export type NftBatchResponse = Schemas["NftBatchResponse"]
export type NftDetailed = Schemas["NftDetailed"]
export type NftIdentifierInput = Schemas["NftIdentifierInput"]
export type NftListResponse = Schemas["NftListResponse"]
export type NftResponse = Schemas["NftResponse"]
export type NftSalePointResponse = Schemas["NftSalePointResponse"]
export type NftSearchResponse = Schemas["NftSearchResponse"]
export type NumericTraitCriteria = Schemas["NumericTraitCriteria"]
export type NumericTraitData = Schemas["NumericTraitData"]
export type Offer = Schemas["Offer"]
export type OfferAggregatePriceResponse = Schemas["OfferAggregatePriceResponse"]
export type OfferItem = Schemas["OfferItem"]
export type OfferObject = Schemas["OfferObject"]
export type OfferWithCriteriaRequest = Schemas["OfferWithCriteriaRequest"]
export type OffersResponse = Schemas["OffersResponse"]
export type OhlcvCandleResponse = Schemas["OhlcvCandleResponse"]
export type OhlcvResponse = Schemas["OhlcvResponse"]
export type Order = Schemas["Order"]
export type OrderAsset = Schemas["OrderAsset"]
export type OrderData = Schemas["OrderData"]
export type OrderEvent = Schemas["OrderEvent"]
export type OrderParameters = Schemas["OrderParameters"]
export type Owner = Schemas["Owner"]
export type OwnersPaginatedResponse = Schemas["OwnersPaginatedResponse"]
export type Parameters = Schemas["Parameters"]
export type PartialParameters = Schemas["PartialParameters"]
export type Payment = Schemas["Payment"]
export type PaymentToken = Schemas["PaymentToken"]
export type PortfolioHistoryDataPoint = Schemas["PortfolioHistoryDataPoint"]
export type PortfolioHistoryResponse = Schemas["PortfolioHistoryResponse"]
export type PortfolioStatsResponse = Schemas["PortfolioStatsResponse"]
export type PositionTokenTransferResponse =
  Schemas["PositionTokenTransferResponse"]
export type PositionTokenTransfersResponse =
  Schemas["PositionTokenTransfersResponse"]
export type Price = Schemas["Price"]
export type PriceHistoryPointResponse = Schemas["PriceHistoryPointResponse"]
export type PriceHistoryResponse = Schemas["PriceHistoryResponse"]
export type PriceResponse = Schemas["PriceResponse"]
export type PricingCurrencies = Schemas["PricingCurrencies"]
export type ProfileCollectionResponse = Schemas["ProfileCollectionResponse"]
export type ProfileCollectionsResponse = Schemas["ProfileCollectionsResponse"]
export type ProtocolData = Schemas["ProtocolData"]
export type Rarity = Schemas["Rarity"]
export type RateLimitsResponse = Schemas["RateLimitsResponse"]
export type RegisteredToolResponse = Schemas["RegisteredToolResponse"]
export type SaleEvent = Schemas["SaleEvent"]
export type SeaportCall = Schemas["SeaportCall"]
export type SeaportParameters = Schemas["SeaportParameters"]
export type SeaportProtocolDataModel = Schemas["SeaportProtocolDataModel"]
export type SeaportRequest = Schemas["SeaportRequest"]
export type SearchResponse = Schemas["SearchResponse"]
export type SearchResultResponse = Schemas["SearchResultResponse"]
export type SocialMediaAccount = Schemas["SocialMediaAccount"]
export type SubscriptionInfoResponse = Schemas["SubscriptionInfoResponse"]
export type SwapAssetInput = Schemas["SwapAssetInput"]
export type SwapCostResponse = Schemas["SwapCostResponse"]
export type SwapExecuteRequest = Schemas["SwapExecuteRequest"]
export type SwapExecuteResponse = Schemas["SwapExecuteResponse"]
export type SwapPriceImpact = Schemas["SwapPriceImpact"]
export type SwapQuoteDetails = Schemas["SwapQuoteDetails"]
export type SwapQuoteInput = Schemas["SwapQuoteInput"]
export type SwapQuoteResponse = Schemas["SwapQuoteResponse"]
export type SwapRouteErrorResponse = Schemas["SwapRouteErrorResponse"]
export type SwapTransactionResponse = Schemas["SwapTransactionResponse"]
export type SweepCollectionRequest = Schemas["SweepCollectionRequest"]
export type SweepCollectionResponse = Schemas["SweepCollectionResponse"]
export type SweepError = Schemas["SweepError"]
export type TokenAmountResponse = Schemas["TokenAmountResponse"]
export type TokenBalancePaginatedResponse =
  Schemas["TokenBalancePaginatedResponse"]
export type TokenBalanceResponse = Schemas["TokenBalanceResponse"]
export type TokenBaseResponse = Schemas["TokenBaseResponse"]
export type TokenBatchResponse = Schemas["TokenBatchResponse"]
export type TokenContractInput = Schemas["TokenContractInput"]
export type TokenDetailedResponse = Schemas["TokenDetailedResponse"]
export type TokenGroupCurrencyResponse = Schemas["TokenGroupCurrencyResponse"]
export type TokenGroupPaginatedResponse = Schemas["TokenGroupPaginatedResponse"]
export type TokenGroupResponse = Schemas["TokenGroupResponse"]
export type TokenGroupRollingStatsResponse =
  Schemas["TokenGroupRollingStatsResponse"]
export type TokenGroupSocialsResponse = Schemas["TokenGroupSocialsResponse"]
export type TokenGroupStatsResponse = Schemas["TokenGroupStatsResponse"]
export type TokenHolderDistributionResponse =
  Schemas["TokenHolderDistributionResponse"]
export type TokenHolderResponse = Schemas["TokenHolderResponse"]
export type TokenHoldersResponse = Schemas["TokenHoldersResponse"]
export type TokenLiquidityPoolResponse = Schemas["TokenLiquidityPoolResponse"]
export type TokenLiquidityPoolsResponse = Schemas["TokenLiquidityPoolsResponse"]
export type TokenPaginatedResponse = Schemas["TokenPaginatedResponse"]
export type TokenResponse = Schemas["TokenResponse"]
export type TokenSearchResponse = Schemas["TokenSearchResponse"]
export type TokenSocialsResponse = Schemas["TokenSocialsResponse"]
export type TokenStatsResponse = Schemas["TokenStatsResponse"]
export type TokenSwapActivityPaginatedResponse =
  Schemas["TokenSwapActivityPaginatedResponse"]
export type TokenSwapActivityResponse = Schemas["TokenSwapActivityResponse"]
export type ToolAccessResponse = Schemas["ToolAccessResponse"]
export type ToolActivityEventResponse = Schemas["ToolActivityEventResponse"]
export type ToolActivityPaginatedResponse =
  Schemas["ToolActivityPaginatedResponse"]
export type ToolCollectionResponse = Schemas["ToolCollectionResponse"]
export type ToolListItemResponse = Schemas["ToolListItemResponse"]
export type ToolListPaginatedResponse = Schemas["ToolListPaginatedResponse"]
export type ToolPaymentStatsResponse = Schemas["ToolPaymentStatsResponse"]
export type ToolPricingRecipientResponse =
  Schemas["ToolPricingRecipientResponse"]
export type ToolRequirementResponse = Schemas["ToolRequirementResponse"]
export type ToolSearchPaginatedResponse = Schemas["ToolSearchPaginatedResponse"]
export type ToolSearchResultResponse = Schemas["ToolSearchResultResponse"]
export type ToolUsageRequest = Schemas["ToolUsageRequest"]
export type ToolUsageResponse = Schemas["ToolUsageResponse"]
export type Total = Schemas["Total"]
export type TotalSpentResponse = Schemas["TotalSpentResponse"]
export type Trait = Schemas["Trait"]
export type TraitCriteria = Schemas["TraitCriteria"]
export type TraitData = Schemas["TraitData"]
export type TraitObject = Schemas["TraitObject"]
export type TransactionData = Schemas["TransactionData"]
export type TransactionIdentifierInput = Schemas["TransactionIdentifierInput"]
export type TransactionReceiptRequest = Schemas["TransactionReceiptRequest"]
export type TransactionReceiptResponse = Schemas["TransactionReceiptResponse"]
export type TransferAsset = Schemas["TransferAsset"]
export type TransferEvent = Schemas["TransferEvent"]
export type TransferRequest = Schemas["TransferRequest"]
export type TransferResponse = Schemas["TransferResponse"]
export type Type = Schemas["Type"]
export type Uint256 = Schemas["Uint256"]
export type V1ErrorWrapper = Schemas["V1ErrorWrapper"]
export type ValidateMetadataAssetIdentifier =
  Schemas["ValidateMetadataAssetIdentifier"]
export type ValidateMetadataAttribute = Schemas["ValidateMetadataAttribute"]
export type ValidateMetadataDetails = Schemas["ValidateMetadataDetails"]
export type ValidateMetadataResponse = Schemas["ValidateMetadataResponse"]
export type WalletLinkResponse = Schemas["WalletLinkResponse"]
export type WalletPnlResponse = Schemas["WalletPnlResponse"]
export type X402SettlementFields = Schemas["X402SettlementFields"]
